### ISSUE TITLE
Max retries exceeded with url /api/1/collection

### ISSUE THREAD

**Issue by bgentry** [twaddington/python-rdio-export#10]
Got this exception running `rdio-export --user myusername`:

```
Traceback (most recent call last):
  File "/usr/local/bin/rdio-export", line 109, in <module>
    sys.exit(main())
  File "/usr/local/bin/rdio-export", line 95, in main
    for t in exporter.collection(user):
  File "/usr/local/lib/python2.7/site-packages/rdio_export/exporter.py", line 88, in collection
    user=user.get('key'), sort=sort, start=start, count=count, extras=extras)
  File "/usr/local/lib/python2.7/site-packages/rdio_export/exporter.py", line 44, in _call
    headers=headers, data=data).json()
  File "/Library/Python/2.7/site-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='services.rdio.com', port=443): Max retries exceeded with url: /api/1/collection (Caused by <class 'socket.error'>: [Errno 60] Operation timed out)
```

**Comment by twaddington** [comment]
Huh, haven't seen that one before. Is your collection pretty big?

**Comment by bgentry** [comment]
> Is your collection pretty big?

yeah, probably :) Not sure how to find the exact count but I'd guess many thousands of songs/albums.

**Comment by twaddington** [comment]
I bumped up the batch size from 50 to 250 in v1.2.1. Let me know if that helps. I might just make that configurable if it's an issue.

**Comment by twaddington** [comment]
You can also throw up a console, import RdioExporter and call the `get_collection` method which fetches it all in one go.

**Comment by bgentry** [comment]
hey thanks, that did the trick! resulting file is 1889 lines, so probably well over 1000 albums.

**Comment by twaddington** [comment]
Nice! Thanks for the update.
