### ISSUE TITLE
rdio-export crashes with JSON parse error.

### ISSUE THREAD

**Issue by WhyNotHugo** [twaddington/python-rdio-export#4]
```
$ rdio-export -k XXX -s YYY -u hobarrera                                                              
Traceback (most recent call last):
  File "/usr/bin/rdio-export", line 96, in <module>
    sys.exit(main())
  File "/usr/bin/rdio-export", line 72, in main
    user = exporter.get_user(username=args.username)
  File "/usr/lib/python2.7/site-packages/rdio_export/exporter.py", line 50, in get_user
    return self._call('social', 'findUser', vanityName=username, extras=extras)
  File "/usr/lib/python2.7/site-packages/rdio_export/exporter.py", line 35, in _call
    auth=self.auth, data=data).json()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 776, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by twaddington** [comment]
Hey, sorry for the delayed replay, GitHub was apparently not sending me notifications on this repository.

I'm not sure why you're getting that error as it's working alright for me. Could have been an issue with the rdio-api?
